"""
recommend_gmm.py
----------------
Content-Based Recommendation Engine using SBERT + GMM embeddings.

Generates recommendations based on the probabilistic soft-assignments 
P(cluster|article) generated by the Gaussian Mixture Model approach.
"""

import os
import sys
import numpy as np
from utils import DATA_PATH, USERS_PATH, load_json

# Force UTF-8 for Windows consoles
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')

def get_gmm_vector(article):
    """Convert article['gmm_topic_vector'] dict to a fixed-length numpy array."""
    vec_dict = article.get('gmm_topic_vector')
    if not vec_dict:
        return np.array([0.0] * 8)
        
    try:
        max_idx = max(int(k.split('_')[1]) for k in vec_dict.keys())
        size = max_idx + 1
    except:
        size = 8
        
    arr = [0.0] * size
    for k, v in vec_dict.items():
        try:
            idx = int(k.split('_')[1])
            arr[idx] = float(v)
        except (IndexError, ValueError):
            pass
    return np.array(arr)

def cosine_similarity(vec_a, vec_b):
    """Cosine similarity between two vectors, safe against zero-norms."""
    norm_a = np.linalg.norm(vec_a)
    norm_b = np.linalg.norm(vec_b)
    if norm_a == 0 or norm_b == 0:
        return 0.0
    return float(np.dot(vec_a, vec_b) / (norm_a * norm_b))


def build_article_index(all_articles):
    """Build a link → article dict so we can look up current GMM vectors by link."""
    return {a['link']: a for a in all_articles if a.get('link')}


def calculate_user_gmm_profile(reading_history, article_index=None):
    """
    Build a user interest vector by averaging the GMM topic vectors of all
    articles in the reading history.

    article_index : optional dict {link: article} from the full corpus.
    If supplied, it is used to fetch the current gmm_topic_vector even when
    the reading-history snapshot pre-dates the GMM run (no gmm_topic_vector
    in the snapshot itself).
    """
    if not reading_history:
        return np.array([])

    first_vec = None
    for snap in reading_history:
        article = article_index.get(snap.get('link'), snap) if article_index else snap
        vec = get_gmm_vector(article)
        if len(vec) > 0:
            first_vec = vec
            break

    if first_vec is None:
        return np.array([])

    total = np.zeros(len(first_vec))
    count = 0
    for snap in reading_history:
        article = article_index.get(snap.get('link'), snap) if article_index else snap
        vec = get_gmm_vector(article)
        
        if len(vec) < len(total):
            padded = np.zeros(len(total))
            padded[:len(vec)] = vec
            vec = padded
        elif len(vec) > len(total):
            vec = vec[:len(total)]
            
        if np.any(vec):
            total += vec
            count += 1

    if count == 0:
        return np.zeros(len(first_vec))
    return total / count


def recommend_articles_gmm(user, all_articles, num_recommendations=5, diversity_score=0.0,
                            article_index=None):
    """
    GMM Content-Based Recommendation Engine.

    Parameters
    ----------
    user                : dict  — user profile with 'reading_history' list
    all_articles        : list  — full article corpus from news_data.json
    num_recommendations : int   — how many articles to return
    diversity_score     : float — 0.0 = pure relevance, 1.0 = pure random
    article_index       : dict  — optional {link: article} lookup built by build_article_index()

    Returns
    -------
    (scored_articles[:num_recommendations], user_vector)
    scored_articles items are tuples: (final_score, similarity, article_dict)
    """
    if article_index is None:
        article_index = build_article_index(all_articles)

    user_vector = calculate_user_gmm_profile(user.get('reading_history', []), article_index)
    read_links  = {a['link'] for a in user.get('reading_history', [])}

    scored = []
    for article in all_articles:
        if not article.get('gmm_topic_vector'):
            continue  # skip articles not yet processed by GMM
        if article['link'] in read_links:
            continue  # already read

        article_vector = get_gmm_vector(article)
        similarity     = cosine_similarity(user_vector, article_vector)
        noise          = np.random.uniform(0.0, 1.0)
        final_score    = (1.0 - diversity_score) * similarity + diversity_score * noise

        scored.append((final_score, similarity, article))

    scored.sort(key=lambda x: x[0], reverse=True)
    return scored[:num_recommendations], user_vector


# ---------------------------------------------------------------------------
# Module Test Implementation
# ---------------------------------------------------------------------------
def main():
    all_articles = load_json(DATA_PATH)
    users        = load_json(USERS_PATH)

    if not all_articles or not users:
        print("Required data files not found. Run previous pipeline scripts first.")
        return

    # Count how many articles have GMM vectors
    gmm_count = sum(1 for a in all_articles if a.get('gmm_topic_vector'))
    if gmm_count == 0:
        print("No GMM topic vectors found in news_data.json.")
        print("Run:  python scripts/run_topic_modeling.py --method gmm")
        return
    print(f"GMM vectors available on {gmm_count} / {len(all_articles)} articles.\n")

    # Build a link → article index so the profile builder can fetch current GMM vectors
    art_index = build_article_index(all_articles)

    test_user = users[0]
    print(f"======== GMM Recommendation Engine — Test ========")
    print(f"User    : {test_user['name']}")
    print(f"Persona : {test_user['description']}")

    # TEST 1: Pure relevance (diversity = 0)
    print("\n--- TEST 1: PURE RELEVANCE (diversity = 0.0) ---")
    recs, user_vec = recommend_articles_gmm(
        test_user, all_articles, num_recommendations=5, diversity_score=0.0,
        article_index=art_index
    )
    top_cluster = int(np.argmax(user_vec))
    print(f"User's top GMM cluster: topic_{top_cluster}  "
          f"(weight={user_vec[top_cluster]:.3f})")
    for rank, (score, sim, article) in enumerate(recs, 1):
        dom = max(article['gmm_topic_vector'], key=article['gmm_topic_vector'].get)
        dom_label = dom.replace('topic_', 'Cluster ')
        print(f"[{rank}] (sim={sim:.3f}) {article['title'][:70]}... [{dom_label}]")

    # TEST 2: High diversity
    print("\n--- TEST 2: HIGH DIVERSITY (diversity = 0.8) ---")
    recs, _ = recommend_articles_gmm(
        test_user, all_articles, num_recommendations=5, diversity_score=0.8,
        article_index=art_index
    )
    for rank, (score, sim, article) in enumerate(recs, 1):
        dom = max(article['gmm_topic_vector'], key=article['gmm_topic_vector'].get)
        dom_label = dom.replace('topic_', 'Cluster ')
        print(f"[{rank}] (final={score:.3f} | sim={sim:.3f}) "
              f"{article['title'][:70]}... [{dom_label}]")

    print("\nGMM Recommendation Framework initialisation tests completed.")


if __name__ == "__main__":
    main()
